openapi: 3.0.1
info:
  title: fa-azurecloudwebresume
  description: ''
  version: '1.0'
servers:
  - url: https://azcloudresume-apim.azure-api.net
paths:
  /GetAzureResume:
    post:
      summary: GetAzureResume
      description: GetAzureResume
      operationId: post-getazureresume
      responses:
        '200':
          description: ''
    get:
      summary: GetAzureResume
      description: GetAzureResume
      operationId: get-getazureresume
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]